### ISSUE TITLE
Driver deserted?

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-ibm#25]
@kderynski and anyone that might be interested. We wanted to check the status of this driver as the main core of `napalm` don't have the means to test and maintain this driver. Is there someone that might be willing to take responsibility of it? Otherwise, we might just deprecate it and leave it here for historical reasons but removing it from the main installation and declaring it unsupported.

**Comment by kderynski** [comment]
@dbarrosop sorry for late response I should definitely fix my mail filters :) Unfortunately I do not have access to any lenovo/ibm switches and there is no VM available, so I am not able to continue work on this. It seems appropriate to remove it from main installation. If anyone will be interested to continue work on this driver I am happy to help. Meanwhile I will try to contribute to other drivers :)

**Comment by dbarrosop** [comment]
Ok, so we should figure out then how to best deprecate this.
